apiVersion: v2
name: retool-with-workflows
description: A Helm chart for Kubernetes
type: application
version: 4.11.10
maintainers:
  - name: Retool Engineering
    email: engineering+helm@retool.com
dependencies:
  - name: postgresql
    version: 12.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: retool-temporal-services-helm
    version: 1.1.0
    condition: workflows.enabled
