apiVersion: v2
appVersion: 1.0.0
dependencies:
- condition: cassandra.enabled
  name: cassandra
  repository: https://charts.helm.sh/incubator
  version: 0.14.3
- condition: prometheus.enabled
  name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 15.1.3
- condition: elasticsearch.enabled
  name: elasticsearch
  repository: https://helm.elastic.co
  version: 7.16.3
- condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 5.0.10
description: A Helm chart for Temporal server for Retool Workflows.
home: https://temporal.io/
keywords:
- temporal
- workflow
- orchestration
maintainers:
- email: engineering+helm@retool.com
  name: Retool Engineering
name: retool-temporal-services-helm
sources:
- https://github.com/temporalio/temporal
type: application
version: 1.0.0
